version: '3.3'
services:
  sqlpal:
    image: sqlpal:latest
    environment:
      IASQL_ENV: ci
    env_file:
      - .env
    ports:
      - "9876:9876"
      - "8088:8088"
    tmpfs:
      - /tmp/indexes
    container_name: sqlpal
  pg:
    container_name: sqlpal_db_pg
    hostname: local_pg
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sqlpaluser
      POSTGRES_PASSWORD: sqlpass
      POSTGRES_DB: sqlpal
    volumes:
      - ./sqlpal-server/fixtures/test_schema.sql:/docker-entrypoint-initdb.d/init.sql
  mysql:
    # mysql://sqlpaluser:sqlpass@local_mysql:3306/sqlpal
    container_name: sqlpal_db_mysql
    hostname: local_mysql
    image: mysql:latest
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "sqlpaluser"
      MYSQL_PASSWORD: "sqlpass"
      MYSQL_DATABASE: "sqlpal"
    volumes:
      - ./sqlpal-server/fixtures/test_schema_mysql.sql:/docker-entrypoint-initdb.d/init.sql
  # mssql:
  #   container_name: sqlpal_db_mssql
  #   hostname: local_mssql
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   ports:
  #     - "1433:1433"
  #   environment:
  #     POSTGRES_PASSWORD: sqlpass
  #     POSTGRES_DB: sqlpal
  #     ACCEPT_EULA: Y
  #     MSSQL_SA_PASSWORD: myStrong(!)Password
  #     MSSQL_PID: Express
  #   volumes:
  #     - ./sqlpal-server/fixtures/test_schema.sql:/docker-entrypoint-initdb.d/init.sql
